Repository approvers/containers, pull requests merged in 2020-09, with the labels that each got.

#32 Add cadocr container
  .github/workflows/deployer.yml
  cadocr/docker-compose.yml
  cadocr/entrypoint.sh
Labels: new

#34 Fix cadocr entrypoint script
  cadocr/entrypoint.sh
Labels: fix

#35 Moving checklist to pull request template
  .github/pull_request_template.md
  README.md
Labels: docs

#36 Update members-db-rust to v1.3.0
  members-db-rust/docker-compose.yml
Labels: update

#38 GitHub Secretary の更新
  githubsecretary/docker-compose.yml
Labels: update
