Repository approvers/containers, pull requests merged in 2020-08, with the labels that each got.

#25 Add imperial police
  .github/workflows/deployer.yml
  imperial_police/docker-compose.yml
Labels: enhancement

#27 Add checklist on README
  README.md
Labels: documentation

#28 Update dockerps-web to v1.1.0
  dockerps-web/docker-compose.yml
Labels: update

#29 Update dockerps-web to v1.1.1
  dockerps-web/docker-compose.yml
Labels: update

#31 Update dockerps-web to 1.2.1
  dockerps-web/docker-compose.yml
Labels: update
